---
title: Writing flexible document outputs with Markdown syntax 
subtitle: "[[ANU BDSI<br>workshop]{.tag-label} Reproducible research with Quarto]{.tag-workshop}"
format:
  anu-light-revealjs:
    width: 1920
    height: 1080
    auto-stretch: false
    html-math-method: katex
    self-contained: true
    css: assets/custom.css
    footer: anu-bdsi.github.io/workshop-intro-quarto/
author: Emi Tanaka
institute: Biological Data Science Institute
date: 2024/04/12
date-format: "D[th] MMMM YYYY"
engine: knitr
---


# Welcome 👋


## Teaching team 

`r photo_path <- ""`

{{< include _team.qmd >}}


# Workshop materials

::: box

All materials will be hosted at<br> [<https://anu-bdsi.github.io/workshop-intro-quarto/>]{.f-subheadline target="_blank"}

:::


## Today's learning objectives 

```{r, include = FALSE}
library(tidyverse)
source("setup.R")
```


```{r}
#| results: asis 
#| echo: false
learning_objectives()
```



## {{< fa crosshairs >}} Current learning objective


```{r}
#| results: asis 
#| echo: false
learning_objectives(1:2)
```